# SECRID  PRODUCT COLLECTION COMPARATIVE ANALYSIS


<span style="color: gray; font-size:1em;">March-2020</span>


## Table of Contents
* [Objective](#objective)

* [Section One - Import Data into IDE](#import_data)
    * [Part I - Gathering Data](#gather_data)
    * [Part II - Assessing Data](#assess_data)
    * [Part III - Cleaning Data](#clean_data)

<a id='objective'></a>
## Objective

The objective of this notebook is to inspect the trend of sales data for 2019 calendar year.

<a id='#import_data'></a>
## Section One : Import Data into IDE

<a id='gather_data'></a>
## Part I : Gathering Data

In [2]:
# load required libraries
import numpy as np
import pandas as pd
from pandas import DataFrame
from pandas import read_excel
import xlsxwriter
import six
from datetime import datetime, timedelta

# environment settings:
pd.options.display.float_format = '{:.2f}'.format
pd.set_option('display.max_column',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.max_seq_items',None)
pd.set_option('display.max_colwidth', 500)
pd.set_option('expand_frame_repr', True)

### Load .xlxs files

In [3]:
#load sales 2019
df = pd.read_excel('SECRID_DATA.xlsx',4)  #load fifth spreadsheet of SECRID DATA.xlxs

<a id='assess_data'></a>
## Part II - Assessing  Data

In [4]:
df.head() #preview first five rows

,Internal ID,Document Number,Date,Date Created,Name,Customer Category,Retailer Role,Shipping Address 1,Shipping Address 2,Shipping City,Shipping Zip,Shipping State/Province,Shipping Country,Item,Display Name,Quantity,Amount,Amount (Foreign Currency),PIM Category,Material,PIM Colour,WSL +,While stock lasts,Cardprotector Colour
0,3441588,I-1900002,2019-01-02,2019-01-02 09:10:00,C-11065 Secrid Warranty EU,Secrid Employee,NaN,28 Randerson drive,NaN,Kilnhurst,S64 5UW,NaN,United Kingdom,MV-Chocolate,Miniwallet Vintage Chocolate,1,0.00,0.00,Miniwallet,Vintage,Brown,No,No,Brown
1,3441589,CN-190001,2019-01-02,2019-01-02 09:11:00,C-7421 Gerton Lederwaren,Leather goods,NaN,De Driehoek 49,NaN,Oldenzaal,7571 ET,NaN,Netherlands,MV-Black,Miniwallet Vintage Black,-1,-22.90,-22.90,Miniwallet,Vintage,Black,No,No,Black
2,3441802,I-1900005,2019-01-02,2019-01-02 09:25:00,C-10244 Secrid Warranty NL,Secrid Employee,NaN,Admiraal de Ruijterweg 243-4,NaN,Amsterdam,1055 LS,NaN,Netherlands,MV-Grey-Black,Miniwallet Vintage Grey-Black,1,0.00,0.00,Miniwallet,Vintage,Grey,No,No,Black
3,3441803,CN-190002,2019-01-02,2019-01-02 09:26:00,C-12479 Projectshop Design RPP GmbH attn. Property of...,Leather goods,NaN,Poststrasse 39,NaN,Hamburg,20354,NaN,Germany,SRa-Green-Gold,Slimwallet Rango Green-Gold,-5,-125.95,-125.95,Slimwallet,Rango,Green,No,Yes,Gold
4,3441803,CN-190002,2019-01-02,2019-01-02 09:26:00,C-12479 Projectshop Design RPP GmbH attn. Property of...,Leather goods,NaN,Poststrasse 39,NaN,Hamburg,20354,NaN,Germany,MC-Black,Miniwallet Crisple Black,-3,-75.57,-75.57,Miniwallet,Crisple,Black,No,No,Black

In [7]:
df.tail() #preview last five rows

,Internal ID,Document Number,Date,Date Created,Name,Customer Category,Retailer Role,Shipping Address 1,Shipping Address 2,Shipping City,Shipping Zip,Shipping State/Province,Shipping Country,Item,Display Name,Quantity,Amount,Amount (Foreign Currency),PIM Category,Material,PIM Colour,WSL +,While stock lasts,Cardprotector Colour
643217,6332393,I-20-SRB-00104,2019-12-07,2020-01-07 13:36:00,C-50195 Secrid Brandstore - Meent 2,Secrid Employee,NaN,Meent 2,NaN,Rotterdam,3011 JJ,NaN,Netherlands,C-Blue,Cardprotector Blue,1,20.62,20.62,Cardprotector,Aluminium,Blue,No,No,Blue
643218,6332393,I-20-SRB-00104,2019-12-07,2020-01-07 13:36:00,C-50195 Secrid Brandstore - Meent 2,Secrid Employee,NaN,Meent 2,NaN,Rotterdam,3011 JJ,NaN,Netherlands,MOr-Black,Miniwallet Ornament Black,1,45.41,45.41,Miniwallet,Ornament,Black,No,No,Black
643219,6332393,I-20-SRB-00104,2019-12-07,2020-01-07 13:36:00,C-50195 Secrid Brandstore - Meent 2,Secrid Employee,NaN,Meent 2,NaN,Rotterdam,3011 JJ,NaN,Netherlands,MM-Green-Black,Miniwallet Matte Green-Black,1,41.28,41.28,Miniwallet,Matte,Green,No,No,Black
643220,6332393,I-20-SRB-00104,2019-12-07,2020-01-07 13:36:00,C-50195 Secrid Brandstore - Meent 2,Secrid Employee,NaN,Meent 2,NaN,Rotterdam,3011 JJ,NaN,Netherlands,C-Lime,Cardprotector Lime,1,20.62,20.62,Cardprotector,Aluminium,Yellow,No,No,Lime
643221,6332393,I-20-SRB-00104,2019-12-07,2020-01-07 13:36:00,C-50195 Secrid Brandstore - Meent 2,Secrid Employee,NaN,Meent 2,NaN,Rotterdam,3011 JJ,NaN,Netherlands,C-Brushed Silver,Cardprotector Brushed Silver,1,20.62,20.62,Cardprotector,Aluminium,Silver,No,No,Brushed Silver

In [8]:
# Check size of the dataframe 
df.shape

(643222, 24)

In [9]:
# list names of columns in dataframe
df.columns

Index(['Internal ID', 'Document Number', 'Date', 'Date Created', 'Name',
       'Customer Category', 'Retailer Role', 'Shipping Address 1',
       'Shipping Address 2', 'Shipping City', 'Shipping Zip',
       'Shipping State/Province', 'Shipping Country', 'Item', 'Display Name',
       'Quantity', 'Amount', 'Amount (Foreign Currency)', 'PIM Category',
       'Material', 'PIM Colour', 'WSL +', 'While stock lasts',
       'Cardprotector Colour'],
      dtype='object')

In [10]:
# View info of the dataframe 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643222 entries, 0 to 643221
Data columns (total 24 columns):
Internal ID                  643222 non-null int64
Document Number              643222 non-null object
Date                         643222 non-null datetime64[ns]
Date Created                 643222 non-null datetime64[ns]
Name                         643222 non-null object
Customer Category            643201 non-null object
Retailer Role                201788 non-null object
Shipping Address 1           642303 non-null object
Shipping Address 2           122071 non-null object
Shipping City                642584 non-null object
Shipping Zip                 642508 non-null object
Shipping State/Province      134683 non-null object
Shipping Country             642799 non-null object
Item                         643222 non-null object
Display Name                 643222 non-null object
Quantity                     643222 non-null int64
Amount                       643222 non-null float64
Amount (Foreign Currency)    643222 non-null float64
PIM Category                 641811 non-null object
Material                     641803 non-null object
PIM Colour                   635626 non-null object
WSL +                        643222 non-null object
While stock lasts            643222 non-null object
Cardprotector Colour         620230 non-null object
dtypes: datetime64[ns](2), float64(2), int64(2), object(18)
memory usage: 117.8+ MB

In [54]:
# view some of the core statistics about columns
df.describe(include='all')

,Internal ID,Document Number,Date,Date Created,Name,Customer Category,Retailer Role,Shipping Address 1,Shipping Address 2,Shipping City,Shipping Zip,Shipping State/Province,Shipping Country,Item,Display Name,Quantity,Amount,Amount (Foreign Currency),PIM Category,Material,PIM Colour,WSL +,While stock lasts,Cardprotector Colour
count,643222.00,643222,643222,643222,643222,643201,201788,642303,122071,642584,642508,134683,642799,643222,643222,643222.00,643222.00,643222.00,641811,641803,635626,643222,643222,620230
unique,nan,56163,290,28095,23160,47,4,25543,3603,7813,20213,299,90,338,334,nan,nan,nan,6,29,47,1,2,20
top,nan,I-1944125,2019-12-12 00:00:00,2019-08-28 09:31:00,C-10625 El Corte Ingles,Leather goods,Availability,"Ctra. Andalucia km. 22.800, S/N",(Madrid),Amsterdam,28343,ON,Netherlands,M-Black,Miniwallet Original Black,nan,nan,nan,Miniwallet,Vintage,Black,No,No,Black
freq,nan,187,7257,208,20363,142752,121852,11996,11996,14905,11996,12607,109400,19140,19140,nan,nan,nan,381639,164142,201292,643222,590938,198578
first,nan,NaN,2019-01-01 00:00:00,2019-01-02 09:10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN
last,nan,NaN,2019-12-31 00:00:00,2020-01-07 13:51:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN
mean,4991565.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.95,68.19,230.27,NaN,NaN,NaN,NaN,NaN,NaN
std,861379.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.20,255.22,4047.31,NaN,NaN,NaN,NaN,NaN,NaN
min,3441588.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1702.00,-20424.00,-306000.00,NaN,NaN,NaN,NaN,NaN,NaN
25%,4109994.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,22.90,22.90,NaN,NaN,NaN,NaN,NaN,NaN
50%,5134826.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,41.28,44.80,NaN,NaN,NaN,NaN,NaN,NaN
75%,5750030.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,67.80,68.70,NaN,NaN,NaN,NaN,NaN,NaN
max,6332393.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.00,54400.00,765000.00,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# check the Data types (dtypes) of each column in Dataframe
df.dtypes

Internal ID                           int64
Document Number                      object
Date                         datetime64[ns]
Date Created                 datetime64[ns]
Name                                 object
Customer Category                    object
Retailer Role                        object
Shipping Address 1                   object
Shipping Address 2                   object
Shipping City                        object
Shipping Zip                         object
Shipping State/Province              object
Shipping Country                     object
Item                                 object
Display Name                         object
Quantity                              int64
Amount                              float64
Amount (Foreign Currency)           float64
PIM Category                         object
Material                             object
PIM Colour                           object
WSL +                                object
While stock lasts                    object
Cardprotector Colour                 object
dtype: object

In [12]:
df.count() #returns the number of non-missing values for each column or row

Internal ID                  643222
Document Number              643222
Date                         643222
Date Created                 643222
Name                         643222
Customer Category            643201
Retailer Role                201788
Shipping Address 1           642303
Shipping Address 2           122071
Shipping City                642584
Shipping Zip                 642508
Shipping State/Province      134683
Shipping Country             642799
Item                         643222
Display Name                 643222
Quantity                     643222
Amount                       643222
Amount (Foreign Currency)    643222
PIM Category                 641811
Material                     641803
PIM Colour                   635626
WSL +                        643222
While stock lasts            643222
Cardprotector Colour         620230
dtype: int64

In [ ]:
#Total missing values(NaN) in a DataFrame
df.isnull().sum().sum()

In [13]:
#Count number of NaN for each column in DataFrame
print(df.isnull().sum())

Internal ID                       0
Document Number                   0
Date                              0
Date Created                      0
Name                              0
Customer Category                21
Retailer Role                441434
Shipping Address 1              919
Shipping Address 2           521151
Shipping City                   638
Shipping Zip                    714
Shipping State/Province      508539
Shipping Country                423
Item                              0
Display Name                      0
Quantity                          0
Amount                            0
Amount (Foreign Currency)         0
PIM Category                   1411
Material                       1419
PIM Colour                     7596
WSL +                             0
While stock lasts                 0
Cardprotector Colour          22992
dtype: int64

<a id='issues'></a>
**Quality issues**
 * Rename column names to have clear, descriptive names in small letters according to best practice. Column 'name' can be renamed to 'customer_name' and column 'material' can be renamed to 'type_of_material'
 * Set to columns to appropriate category data type: 'internal_id', 'document_number', 'customer_name', 'customer _category', 'retailer_role', 'shipping_country', 'item', 'display_name', 'pim_category','type_of_material', 
   'pim_colour', 'wsl', 'while_stock_lasts' and 'cardprotector_colour'

<a id='clean_data'></a>
## Part III - Cleaning Data

In [14]:
# Create copy of original DataFrame
df_copy = df.copy()

In [15]:
#Fixing messy column names
df_copy.columns = df_copy.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

**Test**

In [16]:
# list names of columns in dataframe
df_copy.columns

Index(['internal_id', 'document_number', 'date', 'date_created', 'name',
       'customer_category', 'retailer_role', 'shipping_address_1',
       'shipping_address_2', 'shipping_city', 'shipping_zip',
       'shipping_state/province', 'shipping_country', 'item', 'display_name',
       'quantity', 'amount', 'amount_foreign_currency', 'pim_category',
       'material', 'pim_colour', 'wsl_+', 'while_stock_lasts',
       'cardprotector_colour'],
      dtype='object')

In [17]:
# change column names using rename function
df_copy.rename(columns={                                                 
                         'name':'customer_name',                        
                         'wsl_+':'wsl',
                         'material':'type_of_material' }, 
                 inplace=True)

**Test**

In [18]:
df_copy.columns #List of column names in df_clean Dataframe

Index(['internal_id', 'document_number', 'date', 'date_created',
       'customer_name', 'customer_category', 'retailer_role',
       'shipping_address_1', 'shipping_address_2', 'shipping_city',
       'shipping_zip', 'shipping_state/province', 'shipping_country', 'item',
       'display_name', 'quantity', 'amount', 'amount_foreign_currency',
       'pim_category', 'type_of_material', 'pim_colour', 'wsl',
       'while_stock_lasts', 'cardprotector_colour'],
      dtype='object')

**Define**
<br>Set appropriate data types for fields mentioned in the [Quality issues](#issues)

In [19]:
# use .astype to change data type of dataframe columns
df_copy = df_copy.astype({"internal_id":'category',"document_number":'category',"shipping_address_1":'category',"shipping_address_2":'category',"shipping_city":'category',"shipping_zip":'category',"shipping_state/province":'category', "customer_name":'category', "customer_category":'category', "retailer_role":'category', "shipping_country":'category', "item":'category',"display_name":'category', "pim_category":'category', "type_of_material":'category', "pim_colour":'category',"wsl":'category', "while_stock_lasts":'category', "cardprotector_colour":'category'})

**Test**

In [20]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643222 entries, 0 to 643221
Data columns (total 24 columns):
internal_id                643222 non-null category
document_number            643222 non-null category
date                       643222 non-null datetime64[ns]
date_created               643222 non-null datetime64[ns]
customer_name              643222 non-null category
customer_category          643201 non-null category
retailer_role              201788 non-null category
shipping_address_1         642303 non-null category
shipping_address_2         122071 non-null category
shipping_city              642584 non-null category
shipping_zip               642508 non-null category
shipping_state/province    134683 non-null category
shipping_country           642799 non-null category
item                       643222 non-null category
display_name               643222 non-null category
quantity                   643222 non-null int64
amount                     643222 non-null float64
amount_foreign_currency    643222 non-null float64
pim_category               641811 non-null category
type_of_material           641803 non-null category
pim_colour                 635626 non-null category
wsl                        643222 non-null category
while_stock_lasts          643222 non-null category
cardprotector_colour       620230 non-null category
dtypes: category(19), datetime64[ns](2), float64(2), int64(1)
memory usage: 54.3 MB

In [ ]:
# view some of the core statistics about columns
df_copy.describe(include='all')

<a id='dataset'></a>
## DATASET OF INTEREST

In order to meet the objective, we shall extract the transactions of interest. These are transactions where the quantity is positive (>0) and the amount is positive (>0). This implies that item(s) were sold and revenue was generated for the business.

In [32]:
# rows with positive values in Quantity column and Amount column
# df_clean consits of transactions that bring in revenue
df_clean = df_copy[(df_copy.amount>0) & (df_copy.quantity>0)]

In [37]:
#create new column 'month_name' that registered year sale transaction was held(helps with analysis)
df_clean['month_name'] = df_clean.date.dt.month_name()

C:\Users\waith\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [38]:
#create new column 'month_number' that registered year sale transaction was held(helps with analysis)
df_clean['month_number'] = df_clean.date.dt.month

C:\Users\waith\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

**Test**

In [44]:
df_clean.head() #preview five first rows

,internal_id,document_number,date,date_created,customer_name,customer_category,retailer_role,shipping_address_1,shipping_address_2,shipping_city,shipping_zip,shipping_state/province,shipping_country,item,display_name,quantity,amount,amount_foreign_currency,pim_category,type_of_material,pim_colour,wsl,while_stock_lasts,cardprotector_colour,month,month_number,month_name
21,3441809,I-1900006,2019-01-02,2019-01-02 09:30:00,"C-11541 The Breeze, BVBA",Fashion:Urban/Streetwear Unisex,NaN,Kerkstraat 119,NaN,Blankenberge,8370,NaN,Belgium,C-Black,Cardprotector Black,2,22.40,22.40,Cardprotector,Aluminium,Black,No,No,Black,January,1,January
22,3441809,I-1900006,2019-01-02,2019-01-02 09:30:00,"C-11541 The Breeze, BVBA",Fashion:Urban/Streetwear Unisex,NaN,Kerkstraat 119,NaN,Blankenberge,8370,NaN,Belgium,CS-Black/Black,Cardslide Black/Black,3,68.70,68.70,Cardslide,Polycarbonate,Black,No,No,Black,January,1,January
23,3441809,I-1900006,2019-01-02,2019-01-02 09:30:00,"C-11541 The Breeze, BVBA",Fashion:Urban/Streetwear Unisex,NaN,Kerkstraat 119,NaN,Blankenberge,8370,NaN,Belgium,M-Bordeaux,Miniwallet Original Bordeaux,1,22.90,22.90,Miniwallet,Original,Bordeaux,No,Yes,Bordeaux,January,1,January
24,3441809,I-1900006,2019-01-02,2019-01-02 09:30:00,"C-11541 The Breeze, BVBA",Fashion:Urban/Streetwear Unisex,NaN,Kerkstraat 119,NaN,Blankenberge,8370,NaN,Belgium,SO-Bordeaux,Slimwallet Original Bordeaux,1,22.90,22.90,Slimwallet,Original,Bordeaux,No,Yes,Bordeaux,January,1,January
25,3441809,I-1900006,2019-01-02,2019-01-02 09:30:00,"C-11541 The Breeze, BVBA",Fashion:Urban/Streetwear Unisex,NaN,Kerkstraat 119,NaN,Blankenberge,8370,NaN,Belgium,TO-Black,Twinwallet Original Black,1,33.90,33.90,Twinwallet,Original,Black,No,No,Silver,January,1,January

In [59]:
#Total revenue generated for January - December 2019
sum(amount for amount in df_clean.amount)

44863209.16993468

In [60]:
#Total quantity sales for January - December 2019
sum(qty for qty in df_clean.quantity)

1935494

In [52]:
#Total quantity of items sold and corresponding revenue generated for 2019
qty_revenue_2019= df_clean.groupby(
   ['month_name']
).agg(
    {
         'amount':sum,    # Sum revenue per customer
         'quantity': sum  # get the sum of items sold per year
         
    }
)

qty_revenue_2019.sort_values(by=['amount'], inplace=True, ascending=False)

In [53]:
qty_revenue_2019

               amount  quantity
month_name
December   5990381.79    250402
November   4944890.78    210173
October    4875644.99    209643
August     4127660.54    177103
September  4083629.11    174874
March      3623332.29    162112
July       3310083.64    144251
April      3033928.86    131641
May        2972134.91    127278
January    2958476.97    132060
June       2787206.84    119604
February   2155838.45     96353

In [57]:
#  PIVOT TABLE
qty_revenue_table = pd.pivot_table(df_clean, index="customer_category",columns='month_name',
                              values =["amount","quantity"],aggfunc=sum, margins=True)

#sort the pivot table
qty_revenue_table.sort_values(by=('amount','All'), ascending=False, inplace= True)

In [58]:
qty_revenue_table

                                    amount                                   \
month_name                           April     August   December   February
customer_category
All                             3033928.86 4127606.86 5989477.63 2155793.04
Leather goods                    501232.77  703953.99 1237082.38  378597.40
Luggage/Travel                   429482.25  665355.55  831502.62  238539.68
Department Store                 305487.03  267192.98  662826.75  156560.92
Gift Store                       200749.49  319362.41  313039.66  158654.89
Partners                         176913.11  271147.72  202034.81  207109.64
Stationery                       118364.76  170169.95  206810.73  115911.80
Fashion: Casual: Men & Women     125740.98  197385.80  233346.79   95681.86
Concept/Lifestyle                143171.38  151197.02  217979.26   88782.74
Design Store                     125576.94  166857.33  196051.36   76338.64
Jeweller                          78814.89  123358.38  195323.02   98998.79
Fashion: Casual: Men              71415.24  122788.70  235350.83   44087.52
B2C webshop customer              75186.31   90975.80  230119.00   60474.40
Fashion: Classic: Men             59849.76  106442.90  146700.73   53623.01
Inflight                          71912.61   80218.35   74751.75   14400.00
Fashion                           65151.53  125336.20   84568.03   45927.14
Fashion: Men's                    58363.91   66387.04  137657.52   38216.82
Shoe Store                        60166.17  105726.42   82966.00   53340.26
Fashion: Classic: Men & Women     63752.67   52635.45   87015.36   40612.08
Fashion:Urban/Streetwear Unisex   39994.15   62887.22   71872.68   36619.52
Outdoor                           54139.19   36692.04   62314.43   14112.13
Concept                           26991.09   33646.01   74762.54   23281.18
Airport Store                     27640.80   61856.24   47323.32   28114.13
Webshop                           26913.96   40836.49   70437.67   27495.62
Secrid Employee                    5087.68    8261.15   78810.88   12916.76
Fashion: Urban/Streetwear: Men    26062.99   15163.37   40764.81    6795.40
Sports Store                       7550.39   15832.87   29753.38    8186.01
Home & Living                      8072.13   16427.78   26600.21    6719.60
Fashion: Casual: Women             8887.88    7805.25   18654.88    4745.18
Promotional sales - End user       2557.50     478.99   21882.59    4809.00
Books                             12387.11    6341.22   14066.56    4319.77
Electronics                        8822.16   11269.13   10888.31    2403.42
Tobacconist                        5444.66    9200.01    8260.04    3421.02
Travel retail                      8825.18     837.02    3487.23        nan
Bijouterie                         4784.12    2928.84    4427.01    3020.43
Barber                             1455.76    1206.32    2632.34        nan
Kitchen                            2858.99    3239.28    2538.43        nan
Promotional sales - Reseller       4554.00        nan    2061.00        nan
Marketing                         12500.00        nan    6815.60        nan
Shoe Repair                        2255.08    1192.77    3420.32     709.90
Vendor                              464.44     122.08    7058.96     215.26
Museum                             1097.30    1336.04    2089.34        nan
Fashion: Classic: Women             913.92    1634.32    1448.21     874.11
Fashion: Woman's                       nan     750.56        nan     783.29
Parfumerie                         1057.08    1169.87    1522.15     393.72
Florist / garden center            1279.50        nan        nan        nan
Convenience store                      nan        nan     458.14        nan
Fashion:Urban/Streetwear: Women        nan        nan        nan        nan

                                                                             \
month_name                         January       July       June      March
customer_category
All                             2958452.18 3310083.64 2787206.84 3623278.61
Leather goods                    477406.34  666129.78  471290.74  621222.92
Luggage/Travel                   483014.28  424877.82  399931.91  500395.15
Department Store                 311117.21  238541.41  246796.96  161910.11
Gift Store                       128066.49  175669.71  135538.89  250614.06
Partners                         226705.60  306720.16  187459.67  346769.52
Stationery                       153992.76  176575.45  108634.30  158193.03
Fashion: Casual: Men & Women     126542.69  134823.81  131731.36  166409.81
Concept/Lifestyle                 89398.14  138019.59  154653.71  156667.18
Design Store                      97148.68  141640.73  122905.64  139140.41
Jeweller                         111869.56   88974.97   91095.62  121188.78
Fashion: Casual: Men              60591.63   65763.12   81088.34   94124.09
B2C webshop customer              68849.50   90246.58   79389.46   60932.77
Fashion: Classic: Men             53100.28   61690.32   73954.41  101164.42
Inflight                          92516.79   84352.53   45241.72  122752.08
Fashion                           70763.05   86318.87   61686.03  105485.95
Fashion: Men's                    51158.85   60290.29   39002.32   89709.01
Shoe Store                        65420.23   68417.78   38414.37   52878.01
Fashion: Classic: Men & Women     46328.39   46758.37   43744.45   54278.35
Fashion:Urban/Streetwear Unisex   25741.03   35238.78   34455.51   61566.46
Outdoor                           21759.44   33940.65   36424.41   43534.45
Concept                           14778.97   34653.80   27045.76   35403.37
Airport Store                     25925.68   40935.76   35484.00   14341.96
Webshop                           29736.26   23423.17   28915.73   35605.51
Secrid Employee                    4103.13    9455.37   16271.09   14681.43
Fashion: Urban/Streetwear: Men    12318.12   13251.18   40306.72   19158.97
Sports Store                      28377.72   12421.99    9438.92   12891.95
Home & Living                      7216.91    8003.75    4639.54   17198.68
Fashion: Casual: Women             8078.76    9289.52    6694.38   10318.64
Promotional sales - End user       3802.77     156.07    7339.16    8197.01
Books                             12680.92    7565.32    7571.86    4341.47
Electronics                        9275.20    5590.43    6218.50    5661.50
Tobacconist                        5428.25    4106.31    4232.95   10095.53
Travel retail                     24954.10    5853.06        nan    7655.60
Bijouterie                         2956.67    1191.91    1297.04    1922.25
Barber                             2109.27    2525.28    2333.92     363.38
Kitchen                            1116.42    1490.72     758.35    3176.30
Promotional sales - Reseller           nan     205.94        nan        nan
Marketing                              nan        nan        nan        nan
Shoe Repair                         458.00    1699.31        nan    3435.36
Vendor                              509.18     448.88     665.88    1098.15
Museum                             1247.30     776.60    1353.44    4330.13
Fashion: Classic: Women            1022.57    1578.51        nan        nan
Fashion: Woman's                       nan        nan    1487.83    3118.61
Parfumerie                             nan        nan     373.11     728.71
Florist / garden center             865.04        nan    1338.84        nan
Convenience store                      nan     470.04        nan     617.54
Fashion:Urban/Streetwear: Women        nan        nan        nan        nan

                                                                             \
month_name                             May   November    October  September
customer_category
All                             2972134.91 4944890.78 4875595.41 4083505.27
Leather goods                    510583.14  944120.10  961157.44  863409.85
Luggage/Travel                   448675.85  663905.04  834040.17  530150.70
Department Store                 273700.10  617713.80  442119.04  435222.43
Gift Store                       188663.30  240756.66  330924.42  247517.95
Partners                         121787.90  181941.97  240600.24  199359.24
Stationery                       106876.57  254470.66  222738.63  201167.04
Fashion: Casual: Men & Women     158566.00  204992.15  213307.38  165113.88
Concept/Lifestyle                132692.63  188368.86  164631.86  151211.38
Design Store                     108603.87  191868.68  197557.53  146730.45
Jeweller                          82246.77  183305.59  117140.16  177437.72
Fashion: Casual: Men              64841.98  138536.47  120130.17   88655.96
B2C webshop customer              88476.72  116238.11   90765.92   99403.17
Fashion: Classic: Men             55281.76  144803.91  102217.40   72490.94
Inflight                         177277.35   36749.44   61011.90   83296.93
Fashion                           27723.52  110945.42  120712.22   36881.66
Fashion: Men's                    68953.58   95012.44   71968.57   93789.81
Shoe Store                        59328.66   86334.96   58591.46   64401.32
Fashion: Classic: Men & Women     26557.73   36773.98   57856.23   95424.97
Fashion:Urban/Streetwear Unisex   32479.12   51182.81   76835.88   39520.67
Outdoor                           40781.98   48776.65   72738.24   43448.83
Concept                           39783.91   60101.10   58502.23   46388.54
Airport Store                     28523.03   28844.38   51132.25   40172.10
Webshop                           21363.59   33513.45   39242.08   21418.82
Secrid Employee                   17594.81   85116.32    7736.09    5627.28
Fashion: Urban/Streetwear: Men     8427.57   34360.72    8949.85   26349.55
Sports Store                      19355.17   15661.55   23263.50   19692.62
Home & Living                     12442.52   15888.66   31277.88    9834.53
Fashion: Casual: Women            11913.00   11238.40   30487.52   12451.99
Promotional sales - End user           nan   50404.85   12881.97   17627.39
Books                              6049.62    8908.82   14809.17    8138.76
Electronics                        4574.38   18437.33    5315.49    5864.47
Tobacconist                        7037.87    9083.20    3038.41   11125.07
Travel retail                      8197.91    1259.95   10302.20    6595.40
Bijouterie                         3909.37    5565.67    3795.73    3215.35
Barber                             1889.15    5013.32    5627.53    1659.30
Kitchen                            2186.89    3015.79    2173.79    2783.67
Promotional sales - Reseller        642.89   13072.50    1285.00     243.45
Marketing                              nan        nan    1031.00        nan
Shoe Repair                        1706.14        nan        nan    4842.37
Vendor                               89.33    3722.54    1466.96     566.34
Museum                             1231.70     995.73     988.54     703.55
Fashion: Classic: Women             415.75        nan    2668.91    1906.82
Fashion: Woman's                    701.78    1545.62    1110.07    1275.73
Parfumerie                             nan     277.32    1464.38     387.27
Florist / garden center                nan     967.35        nan        nan
Convenience store                      nan        nan        nan        nan
Fashion:Urban/Streetwear: Women        nan    1098.51        nan        nan

                                             quantity                      \
month_name                              All     April    August  December
customer_category
All                             44861954.03 131641.00 177102.00 250382.00
Leather goods                    8336186.85  22341.00  30940.00  53737.00
Luggage/Travel                   6449871.02  19150.00  27935.00  36757.00
Department Store                 4119188.74  12639.00  11393.00  27978.00
Gift Store                       2689557.93   8498.00  13351.00  13671.00
Partners                         2668549.58  11052.00  16985.00  11932.00
Stationery                       1993905.68   5191.00   6827.00   8449.00
Fashion: Casual: Men & Women     1953642.51   5249.00   7530.00   9328.00
Concept/Lifestyle                1776773.75   6005.00   6772.00   9598.00
Design Store                     1710420.26   5582.00   7203.00   8532.00
Jeweller                         1469754.25   3325.00   5037.00   8109.00
Fashion: Casual: Men             1187374.05   2791.00   4662.00   8509.00
B2C webshop customer             1151057.74   1515.00   1943.00   4178.00
Fashion: Classic: Men            1031319.84   2200.00   4075.00   5353.00
Inflight                          944481.45   2810.00   2908.00   2630.00
Fashion                           941499.62   2867.00   5363.00   3836.00
Fashion: Men's                    870510.16   2557.00   2950.00   6258.00
Shoe Store                        795985.64   2642.00   4270.00   3495.00
Fashion: Classic: Men & Women     651738.03   2655.00   2239.00   3611.00
Fashion:Urban/Streetwear Unisex   568393.83   1727.00   2774.00   2996.00
Outdoor                           508662.44   1874.00   1287.00   2044.00
Concept                           475338.50   1167.00   1515.00   3231.00
Airport Store                     430293.65   1210.00   2828.00   2172.00
Webshop                           398902.35   1246.00   1935.00   3027.00
Secrid Employee                   265661.99    129.00    313.00   2606.00
Fashion: Urban/Streetwear: Men    251909.25   1127.00    694.00   1703.00
Sports Store                      202426.07    252.00    616.00   1183.00
Home & Living                     164322.19    371.00    702.00   1032.00
Fashion: Casual: Women            140565.40    378.00    298.00    725.00
Promotional sales - End user      130137.30    100.00     13.00    757.00
Books                             107180.60    333.00    205.00    526.00
Electronics                        94320.32    393.00    486.00    505.00
Tobacconist                        80473.32    277.00    433.00    375.00
Travel retail                      77967.65    457.00     32.00    163.00
Bijouterie                         39014.39    202.00    125.00    184.00
Barber                             26815.57     57.00     49.00     98.00
Kitchen                            25338.63    132.00    139.00    108.00
Promotional sales - Reseller       22064.78    600.00       nan     90.00
Marketing                          20346.60    250.00       nan    333.00
Shoe Repair                        19719.25     80.00     41.00    131.00
Vendor                             16428.00     23.00      5.00    198.00
Museum                             16149.67     48.00     62.00     89.00
Fashion: Classic: Women            12463.12     40.00     73.00     68.00
Fashion: Woman's                   10773.49       nan     48.00       nan
Parfumerie                          7373.61     45.00     46.00     61.00
Florist / garden center             4450.73     54.00       nan       nan
Convenience store                   1545.72       nan       nan     16.00
Fashion:Urban/Streetwear: Women     1098.51       nan       nan       nan

                                                                        \
month_name                      February   January      July      June
customer_category
All                             96352.00 132059.00 144251.00 119604.00
Leather goods                   17108.00  21437.00  29321.00  20874.00
Luggage/Travel                  10642.00  22452.00  18380.00  17393.00
Department Store                 6398.00  13345.00  10010.00  10182.00
Gift Store                       6996.00   5823.00   7806.00   5851.00
Partners                        12831.00  13647.00  19041.00  11240.00
Stationery                       4796.00   6274.00   6681.00   4604.00
Fashion: Casual: Men & Women     3781.00   5280.00   5353.00   4951.00
Concept/Lifestyle                3970.00   3883.00   5837.00   6656.00
Design Store                     3444.00   4346.00   6271.00   5394.00
Jeweller                         4070.00   4598.00   3648.00   3757.00
Fashion: Casual: Men             1748.00   2606.00   2671.00   3115.00
B2C webshop customer             1203.00   1463.00   1863.00   1650.00
Fashion: Classic: Men            2398.00   2133.00   2265.00   3046.00
Inflight                          700.00   3804.00   3087.00   1650.00
Fashion                          2288.00   3072.00   3768.00   2807.00
Fashion: Men's                   1741.00   2324.00   2773.00   1786.00
Shoe Store                       2277.00   2709.00   2813.00   1535.00
Fashion: Classic: Men & Women    1728.00   2034.00   2009.00   1891.00
Fashion:Urban/Streetwear Unisex  1617.00   1086.00   1569.00   1566.00
Outdoor                           551.00    870.00   1245.00   1244.00
Concept                          1049.00    757.00   1504.00   1262.00
Airport Store                    1390.00   1175.00   1642.00   1513.00
Webshop                          1263.00   1386.00   1048.00   1316.00
Secrid Employee                   480.00     94.00    371.00    633.00
Fashion: Urban/Streetwear: Men    261.00    531.00    632.00   1600.00
Sports Store                      290.00   1221.00    473.00    329.00
Home & Living                     315.00    307.00    360.00    201.00
Fashion: Casual: Women            192.00    328.00    385.00    240.00
Promotional sales - End user      140.00    135.00      5.00    159.00
Books                             126.00    380.00    261.00    250.00
Electronics                       116.00    385.00    265.00    283.00
Tobacconist                       188.00    234.00    179.00    219.00
Travel retail                        nan   1480.00    292.00       nan
Bijouterie                        131.00    158.00     46.00     59.00
Barber                               nan     87.00     95.00    101.00
Kitchen                              nan     49.00     61.00     28.00
Promotional sales - Reseller         nan       nan      8.00       nan
Marketing                            nan       nan       nan       nan
Shoe Repair                        30.00     20.00     75.00       nan
Vendor                              9.00     20.00     19.00     28.00
Museum                               nan     46.00     38.00     47.00
Fashion: Classic: Women            33.00     42.00     64.00       nan
Fashion: Woman's                   36.00       nan       nan     78.00
Parfumerie                         16.00       nan       nan     15.00
Florist / garden center              nan     38.00       nan     51.00
Convenience store                    nan       nan     17.00       nan
Fashion:Urban/Streetwear: Women      nan       nan       nan       nan

                                                                         \
month_name                          March       May  November   October
customer_category
All                             162111.00 127278.00 210173.00 209641.00
Leather goods                    27832.00  23139.00  41856.00  42173.00
Luggage/Travel                   22911.00  19454.00  29014.00  37077.00
Department Store                  6838.00  11055.00  25545.00  18545.00
Gift Store                       10806.00   8342.00  10424.00  13817.00
Partners                         21393.00   7847.00  11135.00  14595.00
Stationery                        6572.00   4482.00  10565.00   8824.00
Fashion: Casual: Men & Women      6554.00   6200.00   7935.00   8370.00
Concept/Lifestyle                 6654.00   5978.00   7775.00   7718.00
Design Store                      6302.00   4960.00   8457.00   8361.00
Jeweller                          4886.00   3403.00   7246.00   4908.00
Fashion: Casual: Men              3602.00   2649.00   5388.00   4717.00
B2C webshop customer              1306.00   1771.00   2295.00   1842.00
Fashion: Classic: Men             3658.00   2065.00   5411.00   3821.00